### ISSUE TITLE
NCEI Minimum Requirements

### ISSUE THREAD

**Issue by mbiddle-nodc** [ioos/cc-plugin-ncei#1]
I've developed a list of the **bare minimum** requirements for NCEI to understand and archive a netCDF file. How should we proceed with implementing these requirements in this plugin?

The thought is, the compliance-checker would provide the robust analysis of the file and there would be some additional output that states if the file meets the NCEI bare minimum to archive. Of course, we always would like to have the most robust metadata as possible, so including the complete checker results would be important. 

Let me know how we should proceed.

**Comment by abirger** [comment]
@mbiddle-nodc , we at IOOS have been working on a similar list for mapping ncSOS parameters on the NetCDF attributes. I believe that it actually may have a lot of similarities with your list. Have you published that list yet?
