### ISSUE TITLE
Python 3 release

### ISSUE THREAD

**Issue by RSully** [ioos/cc-plugin-ncei#15]
Right now using the conda pkg I get an error under Python 3: `missing parentheses in call to 'print' (util.py, line 307)`. It looks like this line is [removed](https://github.com/ioos/cc-plugin-ncei/commit/8d4d814565bba09de76f0731cfc554a3b1cc0fcf#diff-ede241c6b77def1b7baa11c1737c3c64L307) from master, but no release has been made since. I'm not sure if additional changes need to be made or not.

**Comment by RSully** [comment]
For sake of keeping this thread up to date: started in #16, pypi release made, just waiting on conda-forge package.

**Comment by ocefpaf** [comment]
@RSully see https://github.com/conda-forge/cc-plugin-ncei-feedstock/pull/3

PS: Do you want me to add you as a maintainer there?

**Comment by RSully** [comment]
@ocefpaf thanks! They're showing up now. Is it possible to remove py3* packages for the previous version, since they don't work?

re: maintainer, I don't think that is necessary yet, I am just fine forking for the few things I submit :)

**Comment by ocefpaf** [comment]
> re: maintainer, I don't think that is necessary yet, I am just fine forking for the few things I submit :)

You would still need to do that :smile: but you could also merge simple updates. We have a policy that self-merges on updates is OK (and desirable) to avoid delays with new releases.

> Is it possible to remove py3* packages for the previous version, since they don't work?

Done.

**Comment by lukecampbell** [comment]
Hey just to confirm, we're all set with Python 3 now right? @ocefpaf

**Comment by ocefpaf** [comment]
> Hey just to confirm, we're all set with Python 3 now right? @ocefpaf

All can say is that the tests are passing :smile: 

I am not a `ncei` plugin user and never tested this out in the wild. @RSully any comment?
