### ISSUE TITLE
100% Compliance Note

### ISSUE THREAD

**Issue by mbiddle-bcodmo** [ioos/cc-plugin-ncei#26]
If a file gets a perfect score on the NCEI checks, could the checker print something out that says archive ready? (Preferably with confetti and the like...)

**Comment by lukecampbell** [comment]
I don't think compliance checker plugins can change the way the main compliance checker executes. There's nothing communicated to the plugin from the main compliance checker about it's total score or even a hook for printing when it's complete. 

@daf ideas?

**Comment by daf** [comment]
Not plugin specific, but application-wide, the compliance checker does exit with a code (or, is supposed to) depending on if it has errors or not.  So you could always wrap the runner in a bash script or similar and add appropriate fanfare.
