### ISSUE TITLE
release v2.0.2 on conda

### ISSUE THREAD

**Issue by Bobfrat** [ioos/cc-plugin-ncei#45]
@ocefpaf just a placeholder so we don't forget.  I'd be interested in learning how to do the conda releases to take the burden off you.

**Comment by ocefpaf** [comment]
@Bobfrat take a look in the commits in https://github.com/conda-forge/cc-plugin-ncei-feedstock/pull/10

Usually all that is needed is to bump the version and the checksum. That one was too complex b/c I updated the dependencies and re-rendered (this last one can be [done automatically](https://conda-forge.org/docs/webservice.html)).

**Comment by Bobfrat** [comment]
Ok thanks @ocefpaf
