### ISSUE TITLE
Uploading to Conda-forge

### ISSUE THREAD

**Issue by jbosch-noaa** [ioos/cc-plugin-ncei#47]
@ocefpaf  - I recently asked @Bobfrat if this plugin was on Conda -forge.   He said it wasn't and could figure out how to put it there.  He also said you have lots of experience putting software on that repo.  Would you have the time to put the latest NCEI Compliance Checker Plugin on Conda-forge?

**Comment by Bobfrat** [comment]
Thanks @ocefpaf, I updated the readme to reflect this
