### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by ocefpaf** [ioos/cc-plugin-ncei#52]
@MathewBiddle this repository will probably be active again during the code sprint, maybe it is a good time to make this change?

**Comment by MathewBiddle** [comment]
yup. How does this change impact upstream compliance checker? Is that pulling from this repo?

**Comment by ocefpaf** [comment]
> yup. How does this change impact upstream compliance checker? Is that pulling from this repo?

It does but I can send a PR fixing that as soon as you make the change.

**Comment by MathewBiddle** [comment]
done.
`master` is now named `main`

If you have a local clone, you can update it by running the following commands.

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by ocefpaf** [comment]
> > yup. How does this change impact upstream compliance checker? Is that pulling from this repo?
> 
> It does break a single test but I can send a PR fixing that as soon as you make the change.

It turned out we did not test for ncei in complian-checker. I added a test in https://github.com/ioos/compliance-checker/pull/1072 and that already points to the right branch.
