### ISSUE TITLE
ncei-trajectory check sea_name

### ISSUE THREAD

**Issue by mbiddle-nodc** [ioos/cc-plugin-ncei#8]
Checking http://data.nodc.noaa.gov/thredds/dodsC/testdata/mbiddle/GOLD_STANDARD_NETCDF/1.1/NODC_trajectory_template_v1.1_2016-06-14_125322.975680.nc using the ncei-trajectory check, we get.

> sea_name attribute should exist and should be from the NODC sea names list: Cordell Bank National Marine Sanctuary is not a valid sea name

But, in the [seanames table](http://www.nodc.noaa.gov/cgi-bin/OAS/prd/seaname/details/201), we have "Cordell Bank National Marine Sanctuary"

**Comment by lukecampbell** [comment]
The sea names used by the checker for 1.1 are the same that are recommended in the NODC templates page:

https://www.nodc.noaa.gov/General/NODC-Archive/seanamelist.txt

Source: https://www.nodc.noaa.gov/data/formats/netcdf/v1.1/
Search for `sea_name`

**Comment by lukecampbell** [comment]
If someone can point me to a machine-parseable list or database of sea names, I can update it.

**Comment by mbiddle-nodc** [comment]
I'll ask around....

**Comment by lukecampbell** [comment]
@mbiddle-nodc did you ever find out anything about a machine parseable list of sea names?

**Comment by mbiddle-nodc** [comment]
Looking into a possible SKOS endpoint. I'll keep you posted. 

As a note, https://www.nodc.noaa.gov/General/NODC-Archive/seanamelist.txt only contains seanames with IHB codes. So terms like coastal waters or marine sanctuaries wont be listed.

**Comment by mbiddle-nodc** [comment]
Not quite a SKOS endpoint, but:
One can query our vocabulary lookup service thus:

https://www.nodc.noaa.gov/cgi-bin/OAS/lookup?format=xml;table=seanames

**The "value" attribute of each response is the name users should use.**

Note however that one might get multiple responses for each entry in the vocabulary, depending on how one constructs the name of the entry. For example, there are three names for an ISO country, the 2-letter abbreviation, the 3-letter abbreviation, and the long name.

**Comment by kknee** [comment]
@jbosch-noaa any preference on whether we push the release until next week to get the seanames in or release today and push a small patch next week?

**Comment by jbosch-noaa** [comment]
@kknee -Please push the release to next week to get the sea_names in.  Do you have a specific date or time frame in mind (e.g. early vs late next week)?

**Comment by kknee** [comment]
@jbosch-noaa let's say mid-week.  I reset the milestone for 11/3.

**Comment by mbiddle-nodc** [comment]
We also have a response for datatypes (https://www.nodc.noaa.gov/cgi-bin/OAS/lookup?format=xml;table=datatypes) which would be the terms in the ncei_name attribute of the geophysical variable. 

Similarly for instruments (https://www.nodc.noaa.gov/cgi-bin/OAS/lookup?format=xml;table=insttypes) and platforms (https://www.nodc.noaa.gov/cgi-bin/OAS/lookup?format=xml;table=platforms).

**Comment by Bobfrat** [comment]
@mbiddle-nodc so one difference between the seaname list used now: 
https://www.nodc.noaa.gov/General/NODC-Archive/seanamelist.txt

and the new list:
https://www.nodc.noaa.gov/cgi-bin/OAS/lookup?format=xml;table=seanames

is the addition of the NCEI code in the string. For example in the old list we had ```Adriatic Sea``` as compared to now it would need to read ```Adriatic Sea (28I)```. Just wanted to make sure that's ok.

**Comment by mbiddle-nodc** [comment]
Yeah, those are (or supposed to be) the codes from International Hydrographic Bureau, 1953, Limits of Oceans and Seas (Special Publication N° 23), 3rd Edition.  (https://epic.awi.de/29772/1/IHO1953a.pdf).  The NCEI guidance for the sea_name attribute has been 
> The names of the sea in which the data were collected. See the list of NCEI sea names here: NCEI Sea Names (http://www.nodc.noaa.gov/General/NODC-Archive/seanamelist.txt)

We haven't required data providers to include the IHB code in with the sea_name attribute. For example, if data was collected in Chesapeake Bay, we haven't specified that the term in the sea_name attribute should really be 
> :sea_name = Chesapeake Bay (23J)

we've been okay with
> :sea_name = Chesapeake Bay

**Comment by mbiddle-nodc** [comment]
Sorry for all the confusion. Here is a static xml to use for the sea_names check http://www.nodc.noaa.gov/General/NODC-Archive/seanames.xml
